@HOST = http://192.168.2.201:30001

### 首页
GET {{HOST}}

### Blog-添加
POST {{HOST}}/v1/blog
Content-Type: application/json

{
  "userId": "123",
  "title": "title-{{$guid}}",
  "content": "content-{{$guid}}"
}

### Blog-获取列表
GET {{HOST}}/v1/blog
?userId=123

### Blog-获取ById
GET {{HOST}}/v1/blog/202c-123-9223370394630978193

### Blog-批量获取
GET {{HOST}}/v1/blog/batch
?blogId=202c-123-9223370394630978193
&blogId=202c-123-9223370394634241458


### 上传文件 + JSON
POST {{HOST}}/v1/file/upload
Content-Type: multipart/form-data; boundary=12345678

--12345678
Content-Disposition: form-data; name="id"

id-from empty
--12345678
Content-Disposition: form-data; name="pojo"
Content-Type: application/json

{"id":"id-from-json","name":"name-from-json"}
--12345678
Content-Disposition: form-data; name="files"; filename="pom.xml"
Content-Type: application/xml

< ./pom.xml
--12345678
Content-Disposition: form-data; name="files"; filename="README.md"
Content-Type: application/octet-stream

< ./README.md
--12345678--


### actuator
GET {{HOST}}/.actuator
