version: "3"

services:

  zipkin.test:
    image: openzipkin/zipkin
    ports:
      - '9411:9411'

  mysql.test:
    image: mysql:8.0.25
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=no
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=test
    volumes:
      - volume_mysql:/var/lib/mysql
#
#  admin.mysql.test:
#    image: 'phpmyadmin/phpmyadmin:5.1'
#    restart: always
#    environment:
#      - PMA_HOST=mysql.test
#      - PMA_PORT=3306
#      - MYSQL_ROOT_PASSWORD=1234
#      - PMA_ARBITRARY=1
#    ports:
#      - '13306:80'
#    volumes:
#      - volume_admin-mysql:/sessions

  zookeeper-1.test:
    build: zookeeper
    restart: always
    volumes:
      - volume_zookeeper-1:/data

  dubbo-admin.test: # username:password root:root
    image: ghcr.io/linianhui/dubbo-admin:0.3.0
    restart: always
    ports:
      - '30080:8080'

  gateway.example:
    build: gateway
    ports:
      - '30001:80'
      - '15005:5005'

  cms-web.example:
    build: cms-web

  cms-rpc.example:
    build: cms-rpc

volumes:
  volume_mysql:
  volume_admin-mysql:
  volume_zookeeper-1:
