version: "3"

services:

  zipkin.example:
    image: openzipkin/zipkin
    ports:
      - '9411:9411'

  mysql.test:
    image: 'mysql:8.0.25'
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=no
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=test
    volumes:
      - volume_mysql:/var/lib/mysql
#
#  admin.mysql.test:
#    image: 'phpmyadmin/phpmyadmin:5.1'
#    restart: always
#    environment:
#      - PMA_HOST=mysql.test
#      - PMA_PORT=3306
#      - MYSQL_ROOT_PASSWORD=1234
#      - PMA_ARBITRARY=1
#    ports:
#      - '13306:80'
#    volumes:
#      - volume_admin-mysql:/sessions

  gateway.example:
    build:
      context: .
      dockerfile: ./gateway/Dockerfile
      args:
        JAR_FILE: ./gateway/target/gateway-1.jar
    ports:
      - '30001:80'
      - '15005:5005'

  cms.example:
    build:
      context: .
      dockerfile: ./cms/Dockerfile
      args:
        JAR_FILE: ./cms/target/cms-1.jar

volumes:
  volume_mysql:
  volume_admin-mysql:
