version: "3.8"

networks:
  default:
    external:
      name: example-spring-network

services:

  gateway.example:
    build:
      context: example-gateway
      args:
        JAR_FILE: target/example-gateway-1.1.jar
    hostname: gateway.example
    ports:
      - '30001:80'
      - '15005:5005'

  cms-web.example:
    build:
      context: example-cms-web
      args:
        JAR_FILE: target/example-cms-web-1.1.jar
    hostname: cms-web.example
    ports:
      - '15006:5005'

  cms-rpc.example:
    build:
      context: example-cms-rpc
      args:
        JAR_FILE: target/example-cms-rpc-1.1.jar
    hostname: cms-rpc.example
    ports:
          - '15007:5005'
