# https://github.com/linianhui/docker/tree/main/image/mysql-admin/5.1

FROM ghcr.io/linianhui/mysql-admin:5.1

ENV PMA_HOST=mysql.test
ENV PMA_PORT=3306
ENV MYSQL_ROOT_PASSWORD=1234
ENV PMA_ARBITRARY=1

EXPOSE 80