version: "3.8"


networks:
  default:
    external: true
    name: example-spring-network


volumes:
  volume_mysql:
  volume_mysql-admin:
  volume_zookeeper-1:


services:

  alibaba-sentinel.test:
    build: alibaba-sentinel
    hostname: alibaba-sentinel.test
    container_name: infra-alibaba-sentinel
    restart: always
    ports:
      - '10088:80'

  dubbo-admin.test:
    build: dubbo-admin
    hostname: dubbo-admin.test
    container_name: infra-dubbo-admin
    restart: always
    ports:
      - '18080:8080'

  hbase.test:
    build: hbase
    hostname: hbase.test
    container_name: infra-hbase
    restart: always
    ports:
      - '2181:2181'
      - '16010:16010'
      - '16030:16030'

  mysql.test:
    build: mysql
    hostname: mysql.test
    container_name: infra-mysql
    restart: always
    volumes:
      - volume_mysql:/var/lib/mysql

  mysql-admin.test:
    build: mysql-admin
    hostname: mysql-admin.test
    container_name: infra-mysql-admin
    restart: always
    ports:
      - '13306:80'
    volumes:
      - volume_mysql-admin:/sessions

  zipkin.test:
    build: zipkin
    hostname: zipkin.test
    container_name: infra-zipkin
    restart: always
    ports:
      - '19411:9411'

  zookeeper-1.test:
    build: zookeeper
    hostname: zookeeper-1.test
    container_name: infra-zookeeper-1
    restart: always
    ports:
      - '28080:8080'
    volumes:
      - volume_zookeeper-1:/data



