debug: true

server:
  port: 80

spring:
  application:
    name: service1
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    sender:
      type: web
    base-url: http://zipkin.spring-example

management:
  endpoints:
    web:
      exposure:
        include: '*'

lnh.example:
  a: 'a form application.yml'
  b: 'b form application.yml'
