kind: Deployment
apiVersion: apps/v1
metadata:
  name: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: lnhcode/spring-k8s-example-api
          ports:
            - name: http
              containerPort: 8091
