kind: ConfigMap
apiVersion: v1
metadata:
  name: service1
  namespace: spring-example
data:
  application.yml: |-
    lnh.example:
      a: 'k8s config map form application.yml'

---
kind: Service
apiVersion: v1
metadata:
  name: service1
  namespace: spring-example
spec:
  selector:
    app: service1
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: service1
  namespace: spring-example
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service1
  template:
    metadata:
      labels:
        app: service1
    spec:
      containers:
        - name: service1
          image: registry.test/spring-example-service1:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
