kind: ConfigMap
apiVersion: v1
metadata:
  name: service1
  namespace: spring-example
data:
  application.yml: |-
    lnh.example:
      a: 'service1 form k8s configMap application.yml'

---
kind: Service
apiVersion: v1
metadata:
  name: service1
  namespace: spring-example
spec:
  selector:
    app: service1
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: debug
      port: 5005
      targetPort: 5005

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: service1
  namespace: spring-example
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service1
  template:
    metadata:
      labels:
        app: service1
    spec:
      containers:
        - name: service1
          image: registry.test/spring-example-service1:1
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
            - name: debug
              containerPort: 5005
          env:
            - name: spring.profiles.active
              value: prod
          resources:
            requests:
              cpu: 50m
              memory: 256Mi
            limits:
              cpu: 1
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /.actuator/health
              port: 80
            initialDelaySeconds: 20
            timeoutSeconds: 5
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /.actuator/health
              port: 80
            initialDelaySeconds: 20
            timeoutSeconds: 5
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 5
