# https://github.com/linianhui/docker/tree/main/image/hbase/2.4.11

FROM ghcr.io/linianhui/hbase:2.4.11

# 2821  zookeeper client port
EXPOSE 2181

# 16000 hbase master port
EXPOSE 16000

# 16010 hbase master web ui port
EXPOSE 16010

# 16020 hbase regionserver port
EXPOSE 16020

# 16030 hbase regionserver web ui port
EXPOSE 16030