name: test

on: [push]

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: git checkout
        uses: actions/checkout@v1
      - name: test
        env:
          debug: false
        run: ./mvnw.cmd test
