name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      # https://github.com/linianhui/docker/pkgs/container/maven
      image: ghcr.io/linianhui/maven:3.8-openjdk-8

    steps:
      - name: git checkout
        uses: actions/checkout@v1
      - name: test
        env:
          debug: false
        run: mvn test
